package io.curity.identityserver.plugin.OptInMFA;

public enum OptInMFAState
{
    NO_SECOND_FACTOR_CHOSEN,
    SECOND_FACTOR_CHOSEN,
    FIRST_CHOICE_OF_SECOND_FACTOR,
    FIRST_SECOND_FACTOR_CHOSEN,
    FIRST_SECOND_FACTOR_REGISTERED,
    CONFIRM_SCRATCH_CODES,
    SCRATCH_CODES_CONFIRMED
}
